/* EXEMPLO DE COMO TRABALHAR ORGANIZADAMENTE */

-- DATA:
-- CHAMADO:
-- SOLICITANTE:
-- OBJETIVO:

/* Aula 190 - Dicionario de dados */

-- sqlplus system/oracle

-- USUARIO DO BANCO DE DADOS

SHOW USER;

-- TABELA DUMMY (DUAL)

SELECT 1 + 1; -- NÃO FUNCIONA NO ORACLE

SELECT 1 + 1 FROM DUAL;

SELECT 1 + 1 SOMA FROM DUAL; -- COM ALIAS

SELECT 1 + 1 AS SOMA FROM DUAL; -- IDENTIFICANDO O ALIAS COM 'AS'

-- VERIFICANDO O AMBIENTE
-- B023 -> 32 BITS
-- b047 -> 64 BITS

SELECT METADATA FROM SYS.KOPM$;

-- DICIONARIO DE DADOS

SELECT * FROM DICT;

-- INSTANCIA UNICA OU RAC
-- ESTOU UTILIZANDO PARALELISMO?

SELECT PARALLEL FROM V$INSTANCE; -- V$ SIGNIFICA QUE É UMA VIEW

-- ESTRUTURAS DE MEMORIA

SELECT COMPONENT, CURRENT_SIZE, MIN_SIZE, MAX_SIZE 
FROM V$SGA_DYNAMIC_COMPONENTS;

-- CONECTANDO A OUTRO BANCO

SQLPLUS SYSTEM/SENHA@NOMEDOBANCO2
ORACLE_SID=ORCL -- BANCO PADRAO DE CONEXAO

-- NOME DO BANCO

SELECT NAME FROM V$DATABASE;

-- VERSAO DO BANCO

SELECT BANNER FROM V$VERSION;

-- VERIFICAR PRIVILEGIOS DOS USUARIOS

SELECT * FROM USER_SYS_PRIVS;

-- TABELAS DO USUARIO

SELECT TABLE_NAME FROM USER_TABLES;

/* AULA 191 - TABLESPACE E TABELAS */

/*
ARMAZENAMENTO

LOGICO -> TABLESPACE -> SEGMENTOS(OBJETOS) ->
-> EXTENSOES(ESPAÇO) -> BLOCOS(DO SISTEMA OPERACIONAL)

FISICO -> DATAFILES
*/

/* NÃO PODEMOS DETERMINAR EM QUAL ARQUIVO FISICO UM OBJETO
FICARÁ */

CREATE TABLE cursos(
	IDCURSO INT PRIMARY KEY,
	NOME VARCHAR2(30),
	CARGA INT
)TABLESPACE USERS;

CREATE TABLE TESTE(
	IDTESTE INT,
	NOME VARCHAR2(30)
);

-- DICIONARIO DE DADOS

SELECT TABLE_NAME, TABLESPACE_NAME
FROM USER_TABLES; -- MUITA COISA

SELECT TABLE_NAME, TABLESPACE_NAME
FROM USER_TABLES
WHERE TABLE_NAME = 'CURSOS'; -- TABLESPACE USERS
-- 'cursos' EM MINUSCULO NÃO ENCONTRADO

SELECT TABLE_NAME, TABLESPACE_NAME
FROM USER_TABLES
WHERE TABLE_NAME = 'TESTE'; -- TABLESPACE SYSTEM

/* TODO OBJETO POR PADRAO SERA CRIADO NA TABLESPACE USERS
EXCETO QUANDO SE ESTA LOGADO COM O USUARIO SYSTEM, ENTAO O
OBJETO SERA CRIADO NA TABLESPACE SYSTEM */

SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME, BYTES,
BLOCKS, EXTENTS FROM USER_SEGMENTS;

SELECT SEGMENT_NAME, SEGMENT_TYPE, TABLESPACE_NAME, BYTES,
BLOCKS, EXTENTS FROM USER_SEGMENTS
WHERE SEGMENT_NAME = 'CURSOS';

/* AULA 192 - FORMATANDO COLUNAS */

COLUMN TABLESPACE_NAME FORMAT A20; -- A20 20 ESPACOS
COLUMN SEGMENT_NAME FORMAT A10;
COLUMN SEGMENT_TYPE FORMAT A10;

/* AULA 193 - INSTALANDO SQL DEVELOPER */
